### ISSUE TITLE
Text show yellow highlight when wrapped in Row or Column Widget

### ISSUE THREAD

**Issue by pratamarama** [ali-thowfeek/simple_html_css_flutter#1]
when RichText inside Row Widget, the text shows yellow line in front of the text.

![Screen Shot 2020-09-11 at 14 27 11](https://user-images.githubusercontent.com/32236433/92883416-0574a600-f43b-11ea-9e63-2a869dd009cf.png)

normal RichText without wrapped in Row Widget:

![Screen Shot 2020-09-11 at 14 27 19](https://user-images.githubusercontent.com/32236433/92883508-1d4c2a00-f43b-11ea-9846-a389d0cfa8ea.png)

can anybody help me?

**Comment by ali-thowfeek** [comment]
Please take a look at this part in the description

https://github.com/ali-thowfeek/simple_html_css_flutter#workaround-for-text-not-rendering-properly

**Comment by pratamarama** [comment]
> Please take a look at this part in the description
> 
> https://github.com/ali-thowfeek/simple_html_css_flutter#workaround-for-text-not-rendering-properly
> 
> And please let me know if you could get it right. If not, please share some code.

it works, thanks!
