### ISSUE TITLE
Get Extra space in text.

### ISSUE THREAD

**Issue by DipakSkywave** [ali-thowfeek/simple_html_css_flutter#23]
@nohli @ali-thowfeek 
<b>In text show extra space in Text().</b>

return SelectableText.rich(
                                  HTML.toTextSpan(
                                    context,
                                    content,
                                    defaultTextStyle:
                                        showTextWithStyle(
                                            font_size,
                                           Colors.black,
                                            FontWeight.normal),
                                  ),);

This is my code.

**Comment by nohli** [comment]
@DipakSkywave can you please explain what you want exactly?

Is this an issue or a question on how to write code?

Also, please format your code, you could just wrap code with ```.
