### ISSUE TITLE
Error with _stack.removeList() in internals.dart

### ISSUE THREAD

**Issue by manuelvargastapia** [ali-thowfeek/simple_html_css_flutter#4]
I'm using your package to show partial HTML content (no <html>, <body>, etc.) from an unreliable source so that the content may be malformed sometimes (I have no control over the content, it may be a plain string sometimes). I think for a reason related to that, the library throws the following exception: "RangeError (index): Invalid value: Valid value range is empty: -1".

I've tracked the error to the following line in /lib/src/internals.dart: var top = _stack.removeLast();

I don't know the justification for removing the last element from that list. I haven't studied the code deeply enough. I wonder whether a simple validation could do any damage.

Thanks

**Comment by ali-thowfeek** [comment]
Sorry, It's been quite long since I went through the code. Also, most part of this package is written by the original author. 

Although, I think your use case seems to be a little out of the scope of this package. It would be nice If you are able to send a PR.

**Comment by manuelvargastapia** [comment]
Hello. I'm sorry for the delay. Finally, I simply forked the repo to prevent access to the last item if the list is empty. I think this is enough for my use case, but I'll consider submitting a PR if I decide to dig deep on it.
